---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ingress-nginx
  namespace: flux-system
spec:
  path: ./flux/core/ingress-nginx/ingress-nginx/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: metallb-helm-release
    - name: metallb-crs
    - name: tls-certs
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tls-certs
  namespace: flux-system
spec:
  path: ./flux/core/ingress-nginx/ingress-nginx/certificates
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: cert-manager-issuers
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
