argument_specs:
  main:
    short_description: Healthchecks.io role
    options:
      healthchecks_io_platform:
        type: str
        required: true
        choices:
          - linux
          - truenas
          - routeros
          - opnsense
      healthchecks_io_check_name:
        type: str
        required: true
      healthchecks_io_channels_names:
        type: list
        elements: str
        required: true
      healthchecks_io_interval_minutes:
        type: int
        required: true
