apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: searxng
  namespace: ai
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: searxng
      version: "1.0.0"
      sourceRef:
        kind: HelmRepository
        name: searxng
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    searxng:
      config:
        search:
          formats:
            - html
            - json
    env:
      INSTANCE_NAME: "searxng"
      BASE_URL: "https://searxng.${HOMELAB_DOMAIN}"
      AUTOCOMPLETE: "true"
    redis:
      enable: true
      persistentVolumeClaim:
        storageClassName: nfs-ssd
    ingress:
      main:
        enabled: true
        ingressClassName: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "searxng.${HOMELAB_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "SearxNG"
          gethomepage.dev/group: "AI"
          gethomepage.dev/icon: "searxng"
        hosts:
          - host: "searxng.${HOMELAB_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
