---
apiVersion: v1
kind: Service
metadata:
  name: arm
  namespace: ingress-nginx
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  clusterIP: None
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: arm
  namespace: ingress-nginx
subsets:
  - addresses:
      - ip: 10.93.30.17
    ports:
      - name: http
        port: 8080
        protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arm
  namespace: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    external-dns.alpha.kubernetes.io/hostname: "arm.${HOMELAB_DOMAIN}"
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: "Automatic Ripping Machine"
    gethomepage.dev/group: "Media"
    gethomepage.dev/icon: "https://raw.githubusercontent.com/automatic-ripping-machine/automatic-ripping-machine/main/arm/ui/static/img/apple-touch-icon.png"
spec:
  ingressClassName: nginx
  rules:
    - host: "arm.${HOMELAB_DOMAIN}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arm
                port:
                  number: 80
