apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name github-app-privatekey
  namespace: external-secrets
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        private-key: "{{ .privateKey }}"
  dataFrom:
    - extract:
        key: "GitHub External Secrets"
