---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: weave-gitops
  namespace: flux-system
spec:
  path: ./k3s-experimental/core/flux-system/weave-gitops/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
  dependsOn:
    - name: ingress-nginx
    - name: cluster-config
