apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name robusta-substitutions
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SIGNING_KEY: "{{ .signingKey }}"
        ACCOUNT_ID: "{{ .accountID }}"
        SLACK_SINK: "{{ .slackSink }}"
        ROBUSTA_SINK: "{{ .robustaSink }}"
        RSA_PRIVATE: "{{ .rsaPrivate }}"
        RSA_PUBLIC: "{{ .rsaPublic }}"
  data:
    - secretKey: signingKey
      remoteRef:
        key: "Robusta"
        property: "signing_key"
    - secretKey: accountID
      remoteRef:
        key: "Robusta"
        property: "account_id"
    - secretKey: slackSink
      remoteRef:
        key: "Robusta"
        property: "slack_sink"
    - secretKey: robustaSink
      remoteRef:
        key: "Robusta"
        property: "robusta_sink"
    - secretKey: rsaPrivate
      remoteRef:
        key: "Robusta"
        property: "rsa_private"
    - secretKey: rsaPublic
      remoteRef:
        key: "Robusta"
        property: "rsa_public"
