version: "3"

tasks:
  restart-proxmox:
    dir: ansible
    cmds:
      - ansible proxmoxes -i inventory.static.yml -m reboot --become --forks 1
  ansible-setup:
    dir: ansible
    cmds:
      - pip install -r requirements.txt
      - ansible-galaxy install -r requirements.yml --force
  ansible-facts:
    dir: ansible
    cmds:
      - ansible -m setup {{.CLI_ARGS}}
  ansible-lint:
    dir: ansible
    cmds:
      - ansible-lint -c .ansible-lint
  prettier:
    cmds:
      - prettier --write .
  docs:
    cmds:
      - mkdocs serve
  linters:
    cmds:
      - task: ansible-lint
      - task: prettier
  experimental:
    cmds:
      - git fetch --tags --force
      - git tag --force experimental
      - git push origin experimental --force
