apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-healthchecks-io
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ping-healthchecks-io
              image: quay.io/curl/curl:8.17.0@sha256:f6710cb71617689b9e3522bde531a1a59f3d39e848be4cb450c9f87c5d15c3a5
              imagePullPolicy: Always
              args:
                - "-fsS"
                - "-m"
                - "10"
                - "--retry"
                - "5"
                - "https://hc-ping.com/${HC_K8S_CHECK_UUID}"
          restartPolicy: OnFailure
