apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-healthchecks-io
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: ping-healthchecks-io
              image: quay.io/curl/curl:8.16.0@sha256:b17b133216781da3255a09e3a5a685f58fb7f7a9a001e7402e6230ec1d65419b
              imagePullPolicy: Always
              args:
                - "-fsS"
                - "-m"
                - "10"
                - "--retry"
                - "5"
                - "https://hc-ping.com/${HC_K8S_CHECK_UUID}"
          restartPolicy: OnFailure
