apiVersion: batch/v1
kind: CronJob
metadata:
  name: ping-healthchecks-io
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      activeDeadlineSeconds: 300
      backoffLimit: 1
      ttlSecondsAfterFinished: 3600
      template:
        spec:
          containers:
            - name: ping-healthchecks-io
              image: quay.io/curl/curl:8.22.0@sha256:58adaa4e8dca9c988bae2aba4ab3434a0bb2da16bbe3f92dec39ec7785166777
              imagePullPolicy: Always
              args:
                - "-fsS"
                - "-m"
                - "10"
                - "--retry"
                - "5"
                - "https://hc-ping.com/${HC_K8S_CHECK_UUID}"
          restartPolicy: OnFailure
