apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mikrotik-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-mikrotik-exporter
      sourceRef:
        kind: GitRepository
        name: mikrotik-prometheus-exporter
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: nshttpd/mikrotik-exporter
      tag: 1.0.11
    config:
      devices:
        - name: "gce.${HOMELAB_DOMAIN}"
          address: "192.168.2.2"
          user: "${MIKROTIK_GCE_PROMETHEUS_USERNAME}"
          password: "${MIKROTIK_GCE_PROMETHEUS_PASSWORD}"
      features:
        dhcp: true
        dhcpl: true
        firmware: true
        health: true
        monitor: true
        optics: true
    secretConfig: true
    configmapReload:
      image:
        repository: jimmidyson/configmap-reload
        tag: v0.9.0
