apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mikrotik-exporter
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: http
  namespaceSelector:
    matchNames:
      - monitoring
  selector:
    matchLabels:
      app.kubernetes.io/instance: mikrotik-exporter
      app.kubernetes.io/name: prometheus-mikrotik-exporter
