apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name external-dns
  namespace: external-dns
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        api-token: "{{ .token }}"
  dataFrom:
    - extract:
        key: "Cloudflare"
