apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: influxdb2
      version: 2.1.2
      sourceRef:
        kind: HelmRepository
        name: influxdata
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    fullnameOverride: influxdb
    adminUser:
      organization: homelab
      user: admin
    persistence:
      enabled: false
      storageClass: nfs-ssd
      accessMode: ReadWriteOnce
      size: 50Gi
      mountPath: /var/lib/influxdb2
      subPath: ""
    ingress:
      enabled: true
      className: nginx
      tls: true
      hostname: influxdb.${HOMELAB_DOMAIN}
      path: /
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "influxdb.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "InfluxDB"
        gethomepage.dev/group: "Monitoring"
        gethomepage.dev/icon: "influxdb"
        gethomepage.dev/pod-selector: >-
          app.kubernetes.io/name=influxdb2
