apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: n8n
  namespace: flux-system
spec:
  path: ./k3s-stable/apps/life-automations/n8n/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: storage-classes
    - name: cluster-config
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
