apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: spoolman
  namespace: spoolman
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controllers:
      app:
        containers:
          app:
            image:
              repository: ghcr.io/donkie/spoolman
              tag: 0.22.1
            env:
              TZ: "Europe/Warsaw"
    service:
      app:
        controller: app
        ports:
          http:
            port: 8000
    ingress:
      main:
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "spoolman.${HOMELAB_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Spoolman"
          gethomepage.dev/group: "Web"
          gethomepage.dev/icon: "spoolman"
          gethomepage.dev/widget.type: "spoolman"
          gethomepage.dev/widget.url: "https://spoolman.${HOMELAB_DOMAIN}"
        hosts:
          - host: "spoolman.${HOMELAB_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      app:
        existingClaim: spoolman
        advancedMounts:
          app:
            app:
              - path: "/home/app/.local/share/spoolman"
