apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name prometheus-substitutions
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        HOMEASSISTANT_TOKEN: "{{ .homeassistantToken }}"
  data:
    - secretKey: homeassistantToken
      remoteRef:
        key: "Homeassistant"
        property: "token"
