apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name homepage-substitutions
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        TRUENAS_API_KEY: "{{ .truenasApiKey }}"
        PROXMOX_HOMEPAGE_API_SECRET: "{{ .proxmoxHomepageApiSecret }}"
        PROXMOX_HOMEPAGE_API_TOKEN_ID: "{{ .proxmoxHomepageApiTokenId }}"
        HOMEASSISTANT_TOKEN: "{{ .homeassistantToken }}"
        MIKROTIK_GCE_PASSWORD: "{{ .mikrotikGcePassword }}"
        MIKROTIK_GCE_USERNAME: "{{ .mikrotikGceUsername }}"
        OPNSENSE_API_KEY: "{{ .opnsenseApiKey }}"
        OPNSENSE_API_SECRET: "{{ .opnsenseApiSecret }}"
        JELLYFIN_TOKEN: "{{ .jellyfinToken }}"
        QBITTORRENT_USERNAME: "{{ .qbittorrentUsername }}"
        QBITTORRENT_PASSWORD: "{{ .qbittorrentPassword }}"
  data:
    - secretKey: truenasApiKey
      remoteRef:
        key: "TrueNAS"
        property: "api_key"
    - secretKey: proxmoxHomepageApiSecret
      remoteRef:
        key: "Proxmox homepage"
        property: "secret"
    - secretKey: proxmoxHomepageApiTokenId
      remoteRef:
        key: "Proxmox homepage"
        property: "token_id"
    - secretKey: homeassistantToken
      remoteRef:
        key: "Homeassistant"
        property: "token"
    - secretKey: mikrotikGcePassword
      remoteRef:
        key: "Router GCE homepage"
        property: "password"
    - secretKey: mikrotikGceUsername
      remoteRef:
        key: "Router GCE homepage"
        property: "username"
    - secretKey: opnsenseApiKey
      remoteRef:
        key: "OPNsense homepage"
        property: "api_key"
    - secretKey: opnsenseApiSecret
      remoteRef:
        key: "OPNsense homepage"
        property: "api_secret"
    - secretKey: jellyfinToken
      remoteRef:
        key: "Jellyfin"
        property: "token"
    - secretKey: qbittorrentUsername
      remoteRef:
        key: "qBittorrent"
        property: "username"
    - secretKey: qbittorrentPassword
      remoteRef:
        key: "qBittorrent"
        property: "password"
