apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name grafana-substitutions
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        GRAFANA_USER: "{{ .grafanaUser }}"
        GRAFANA_PASSWORD: "{{ .grafanaPassword }}"
  data:
    - secretKey: grafanaUser
      remoteRef:
        key: "Grafana"
        property: "username"
    - secretKey: grafanaPassword
      remoteRef:
        key: "Grafana"
        property: "password"
