apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name changedetection-substitutions
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        CD_API_KEY: "{{ .CDApiKey }}"
  data:
    - secretKey: CDApiKey
      remoteRef:
        key: "Changedetection.io"
        property: "api_key"
