apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name prometheus-substitutions
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        PIKVM_USERNAME: "{{ .pikvmUsername }}"
        PIKVM_PASSWORD: "{{ .pikvmPassword }}"
        HOMEASSISTANT_TOKEN: "{{ .homeassistantToken }}"
  data:
    - secretKey: pikvmUsername
      remoteRef:
        key: "PiKVM"
        property: "username"
    - secretKey: pikvmPassword
      remoteRef:
        key: "PiKVM"
        property: "password"
    - secretKey: homeassistantToken
      remoteRef:
        key: "Homeassistant"
        property: "token"
