---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pve-exporter
  namespace: flux-system
spec:
  path: ./k3s-stable/apps/monitoring/pve-exporter/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: kube-prometheus-stack
    - name: cluster-config
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
