apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ai
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: open-webui
      version: "3.0.10"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    ingress:
      enabled: true
      class: nginx
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "ollama-ui.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Ollama UI"
        gethomepage.dev/group: "AI"
        gethomepage.dev/icon: "ollama"
      host: "ollama-ui.${HOMELAB_DOMAIN}"
    ollama:
      enabled: false
    ollamaUrls:
      - "ollama.ai.svc.cluster.local"
    persistence:
      storageClass: nfs-ssd
