apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: open-webui
  namespace: ai
spec:
  interval: 30m
  timeout: 15m
  chart:
    spec:
      chart: open-webui
      version: "3.4.3"
      sourceRef:
        kind: HelmRepository
        name: open-webui
        namespace: flux-system
  install:
    crds: Create
    remediation:
      retries: 5
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 5
  values:
    extraEnvVars:
      - name: "DEFAULT_USER_ROLE"
        value: "user"
      - name: "ENABLE_COMMUNITY_SHARING"
        value: "false"
      - name: "RAG_EMBEDDING_ENGINE"
        value: "ollama"
      - name: "ENABLE_RAG_WEB_SEARCH"
        value: "true"
      - name: "RAG_WEB_SEARCH_ENGINE"
        value: "searxng"
      - name: "SEARXNG_QUERY_URL"
        value: "http://searxng.ai.svc.cluster.local:8080/search?q=<query>"
    ingress:
      enabled: true
      class: nginx
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "ollama-ui.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Ollama UI"
        gethomepage.dev/group: "AI"
        gethomepage.dev/icon: "ollama"
      host: "ollama-ui.${HOMELAB_DOMAIN}"
    ollama:
      enabled: false
    ollamaUrls:
      - "http://ollama.ai.svc.cluster.local:11434"
    persistence:
      storageClass: nfs-ssd
