ansible_user: andrzej3393
ansible_password: "{{ lookup('community.general.onepassword', 'k3s-stable', vault='Homelab', section='andrzej3393', field='password') }}"

users:
  - login: "root"
    password: "{{ lookup('community.general.onepassword', 'k3s-stable', vault='Homelab', section='root', field='password') }}"
    ssh_public_keys: "{{ ssh_public_keys }}"
  - login: "andrzej3393"
    password: "{{ lookup('community.general.onepassword', 'k3s-stable', vault='Homelab', section='andrzej3393', field='password') }}"
    ssh_public_keys: "{{ ssh_public_keys }}"
    passwordless_sudo: true

network_host: 24
configure_vlans:
  - "{{ network_vlans.management }}"
  - "{{ network_vlans.services }}"
  - "{{ network_vlans.nfs }}"

proxmox_vmid: 102
proxmox_vm_memory: 4096
proxmox_vm_cores: 2
proxmox_vm_disk: 20
proxmox_vm_create_tags:
  - k3s
  - k3s-master

# renovate: datasource=github-releases depName=k3s-io/k3s
k3s_release_version: "v1.34.1+k3s1"
k3s_install_hard_links: true
k3s_become: true
k3s_management_interface: eth0
k3s_server:
  disable:
    - traefik
    - servicelb
  tls-san: "{{ ansible_host }}"
  node-ip: "{{ ansible_host }}"
  flannel-backend: "none"
  disable-kube-proxy: true
  disable-network-policy: true
  node-taint:
    - "node.cilium.io/agent-not-ready:NoSchedule"

# renovate: datasource=github-releases depName=cilium/cilium
cilium_chart_version: "1.18.2"
