---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb.yaml
  - weaveworks.yaml
  - ingress-nginx.yaml
  - external-dns.yaml
  - 1password.yaml
  - jetstack.yaml
  - jameswynn.yaml
  - csi-driver-nfs.yaml
  - fairwinds.yaml
  - bjw-s.yaml
  - influxdata.yaml
  - kyverno.yaml
  - prometheus-community.yaml
  - christianknell.yaml
  - mikrotik-prometheus-exporter.yaml
  - external-secrets.yaml
  - robusta.yaml
  - cnpg.yaml
  - intel.yaml
  - nfd.yaml
