---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable-diffusion-webui
  namespace: flux-system
spec:
  interval: 1h
  url: https://amithkk.github.io/stable-diffusion-k8s/
