---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mosquitto
  namespace: flux-system
spec:
  path: ./k3s-stable/apps/home-assistant/mosquitto/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
  dependsOn:
    - name: cluster-config
    - name: storage-classes
    - name: ingress-nginx
