- name: Install configd action
  ansible.builtin.template:
    src: configd_action.j2
    dest: /usr/local/opnsense/service/conf/actions.d/actions_scrutiny.conf
    owner: root
    group: wheel
    mode: "0644"
  become: true
  notify: Restart configd service

- name: Flush handlers
  meta: flush_handlers

- name: Create cronjob
  delegate_to: localhost
  ansibleguy.opnsense.cron:
    firewall: "{{ hostvars[inventory_hostname].opnsense_firewall }}"
    ssl_verify: "{{ hostvars[inventory_hostname].opnsense_ssl_verify }}"
    api_key: "{{ hostvars[inventory_hostname].opnsense_api_key }}"
    api_secret: "{{ hostvars[inventory_hostname].opnsense_api_secret }}"
    description: "{{ scrutiny_collector_cronjob_name }}"
    command: "scrutiny collect"
    minutes: "0"
    hours: "*/{{ scrutiny_collector_interval_hours }}"
