---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: esphome-config
  namespace: home-assistant
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 1Gi
