---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: csi-driver-nfs
  namespace: flux-system
spec:
  path: ./k3s-experimental/core/storage/csi-driver-nfs/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: storage-classes
  namespace: flux-system
spec:
  path: ./k3s-experimental/core/storage/csi-driver-nfs/storage-classes
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
  dependsOn:
    - name: csi-driver-nfs
