apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.18.1
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: cilium-values
