apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: &name ghcr-pull
spec:
  externalSecretName: *name
  namespaceSelector:
    matchLabels:
      ghcr-secrets: "true"
  externalSecretSpec:
    secretStoreRef:
      name: op-connect
      kind: ClusterSecretStore
    target:
      name: *name
      template:
        engineVersion: v2
        type: kubernetes.io/dockerconfigjson
        data:
          .dockerconfigjson: |
            {"auths": {"ghcr.io": {"auth": "{{ printf "%s:%s" .username .token | b64enc }}"}}}
    dataFrom:
      - extract:
          key: "GitHub Packages"
