apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cloudflare-api-token-secret
  namespace: cert-manager
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        token: "{{ .token }}"
  dataFrom:
    - extract:
        key: "Cloudflare"
