apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gha-secrets-store
  namespace: flux-system
spec:
  path: ./k3s-stable/core/external-secrets/gha-secrets/store
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gha-secrets-source
  namespace: flux-system
spec:
  path: ./k3s-stable/core/external-secrets/gha-secrets/source
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: external-secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gha-secrets-destination
  namespace: flux-system
spec:
  path: ./k3s-stable/core/external-secrets/gha-secrets/destination
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: gha-secrets-store
    - name: gha-secrets-source
