---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-config
  namespace: flux-system
spec:
  path: ./k3s-experimental/core/flux-system/substitutions/secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: external-secrets
