apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: n8n-db
  namespace: life-automations
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.7
  instances: 1
  storage:
    size: 5Gi
    storageClass: nfs-ssd
