---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: n8n
  namespace: life-automations
spec:
  interval: 15m
  chart:
    spec:
      chart: n8n
      version: 1.0.7
      sourceRef:
        kind: HelmRepository
        name: n8n
        namespace: flux-system
      interval: 15m
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: n8nio/n8n
      tag: 1.102.0
    ingress:
      enabled: true
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "n8n.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "N8N"
        gethomepage.dev/group: "Automations"
        gethomepage.dev/icon: "n8n"
      className: nginx
      hosts:
        - host: "n8n.${HOMELAB_DOMAIN}"
          paths:
            - /
    main:
      config:
        db:
          type: postgresdb
        generic:
          timezone: Europe/Warsaw
        n8n:
          editor:
            base:
              url: "https://n8n.${HOMELAB_DOMAIN}/"
          default:
            locale: pl
      extraEnv:
        DB_POSTGRESDB_DATABASE:
          valueFrom:
            secretKeyRef:
              name: n8n-db-app
              key: dbname
        DB_POSTGRESDB_HOST:
          valueFrom:
            secretKeyRef:
              name: n8n-db-app
              key: host
        DB_POSTGRESDB_PORT:
          valueFrom:
            secretKeyRef:
              name: n8n-db-app
              key: port
        DB_POSTGRESDB_USER:
          valueFrom:
            secretKeyRef:
              name: n8n-db-app
              key: username
        DB_POSTGRESDB_PASSWORD:
          valueFrom:
            secretKeyRef:
              name: n8n-db-app
              key: password
      persistence:
        enabled: true
        type: existing
        existingClaim: n8n-data
      resources:
        limits:
          cpu: 200m
          memory: 512Mi
        requests:
          cpu: 100m
          memory: 256Mi
