apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name slack-token
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        address: "{{ .address }}"
  dataFrom:
    - extract:
        key: "Flux Slack"
