- name: Create namespace
  delegate_to: localhost
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: external-secrets
    state: present
    context: "{{ inventory_hostname }}"

- name: Create op-connect secrets
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    template: secrets.yml.j2
    context: "{{ inventory_hostname }}"
