---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: mosquitto
      version: 2.4.1
      sourceRef:
        kind: HelmRepository
        name: t3n
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: eclipse-mosquitto
      tag: 1.6.12
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: nfs-ssd
