---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2beta2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: mosquitto
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      mosquitto:
        containers:
          app:
            image:
              repository: eclipse-mosquitto
              tag: 2.0.20
    service:
      app:
        enabled: true
        controller: mosquitto
        ports:
          http:
            port: 8883
    ingress:
      app:
        enabled: true
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "mosquitto.${HOMELAB_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "MQTT"
          gethomepage.dev/group: "Automations"
          gethomepage.dev/icon: "mqtt"
        hosts:
          - host: "mosquitto.${HOMELAB_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http
    persistence:
      data:
        existingClaim: mosquitto-data
        globalMounts:
          - path: /mosquitto/data
      config:
        type: configMap
        name: mosquitto-config
        globalMounts:
          - path: /mosquitto/config
    configMaps:
      config:
        enabled: true
        data:
          mosquitto.conf: |-
            persistence true
            persistence_location /mosquitto/data/

            per_listener_settings true

            log_dest stdout

            listener 8883
            protocol mqtt

            allow_anonymous true
