---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfd
  namespace: flux-system
spec:
  path: ./k3s-stable/core/kube-system/nfd/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nfd-rules
  namespace: flux-system
spec:
  path: ./k3s-stable/core/kube-system/nfd/rules
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: nfd
