- name: Add cilium repo
  delegate_to: localhost
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: https://helm.cilium.io/
    force_update: true

- name: Deploy cilium
  delegate_to: localhost
  kubernetes.core.helm:
    chart_ref: cilium/cilium
    chart_version: "{{ cilium_chart_version }}"
    name: cilium
    namespace: cilium
    create_namespace: true
    context: "{{ inventory_hostname }}"
    values_files:
      - "{{ inventory_dir }}/../{{ inventory_hostname }}/core/cilium/cilium/app/values.yaml"

- name: Deploy Cilium LB IP Pool
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    context: "{{ inventory_hostname }}"
    src: "{{ inventory_dir }}/../{{ inventory_hostname }}/core/cilium/cilium/crs/lb_ip_pool.yaml"
  retries: 5
  delay: 5

- name: Deploy Cilium L2 Announcement Policy
  delegate_to: localhost
  kubernetes.core.k8s:
    state: present
    context: "{{ inventory_hostname }}"
    src: "{{ inventory_dir }}/../{{ inventory_hostname }}/core/cilium/cilium/crs/l2_announcement_policy.yaml"
