apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name drive-invoices-gcp-token
  namespace: life-automations
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
  data:
    - secretKey: token.json
      remoteRef:
        key: "Drive Invoices GCP Token"
        property: "token.json"
