---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drive-invoices-token
  namespace: life-automations
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 1Mi
