apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name cluster-user-auth
  namespace: flux-system
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        password: "{{ .password | bcrypt }}"
        username: "{{ .username }}"
  dataFrom:
    - extract:
        key: "Weave Gitops"
