---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbittorrent
  namespace: high-seas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 1Gi
