---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-dns
  namespace: flux-system
spec:
  path: ./k3s-experimental/core/external-dns/external-dns/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  dependsOn:
    - name: cluster-config
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
