apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: speedtest
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 5Gi
