- name: Reboot
  become: true
  ansible.builtin.reboot:
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    msg: "Rebooting to apply updates"
    test_command: /usr/bin/rw

- name: Remind about firmware upgrade
  ansible.builtin.debug:
    msg: "Don't forget to upgrade firmware on {{ inventory_hostname }}!"
