---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-tls
  namespace: cert-manager
spec:
  secretName: homelab-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "experimental.${HOMELAB_DOMAIN}"
    - "*.experimental.${HOMELAB_DOMAIN}"
