apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name scrutiny
  namespace: monitoring
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        SCRUTINY_NOTIFY_URLS: "{{ .webhook }}"
  dataFrom:
    - extract:
        key: "Scrutiny Slack"
