---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: scrutiny-config
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 1Gi
