- name: Pull updates
  delegate_to: localhost
  ansibleguy.opnsense.system:
    firewall: "{{ hostvars[inventory_hostname].opnsense_firewall }}"
    ssl_verify: "{{ hostvars[inventory_hostname].opnsense_ssl_verify }}"
    api_key: "{{ hostvars[inventory_hostname].opnsense_api_key }}"
    api_secret: "{{ hostvars[inventory_hostname].opnsense_api_secret }}"
    action: "update"

- name: Start upgrade
  delegate_to: localhost
  ansibleguy.opnsense.system:
    firewall: "{{ hostvars[inventory_hostname].opnsense_firewall }}"
    ssl_verify: "{{ hostvars[inventory_hostname].opnsense_ssl_verify }}"
    api_key: "{{ hostvars[inventory_hostname].opnsense_api_key }}"
    api_secret: "{{ hostvars[inventory_hostname].opnsense_api_secret }}"
    action: "upgrade"
    timeout: 600
