---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: z2m-garage
  namespace: home-assistant
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: zigbee2mqtt
      version: 2.6.1
      sourceRef:
        kind: HelmRepository
        name: z2m
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 2.6.2@sha256:ffabf256f4550175278fbeebdbc3f174f2ffa005175e755324c5f06020af3e68
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: "zigbee2mqtt-garage.${HOMELAB_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
            - path: /api
              pathType: ImplementationSpecific
      tls:
        - hosts:
          - "zigbee2mqtt-garage.${HOMELAB_DOMAIN}"
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "zigbee2mqtt-garage.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Zigbee2MQTT Garage"
        gethomepage.dev/group: "Automations"
        gethomepage.dev/icon: "zigbee2mqtt"
    statefulset:
      storage:
        enabled: true
        storageClassName: nfs-ssd
    zigbee2mqtt:
      mqtt:
        server: "mqtt://mosquitto.home-assistant.svc.cluster.local:8883"
        base_topic: zigbee2mqtt_garage
      serial:
        port: "tcp://192.168.34.2:6638"
        adapter: "zstack"
        baudrate: 115200
        disable_led: false
      advanced:
        transmit_power: 20
