apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name pve-exporter
  namespace: monitoring
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
    template:
      engineVersion: v2
      data:
        password: "{{ .password }}"
        user: "{{ .username }}@{{ .realm }}"
  dataFrom:
    - extract:
        key: "Proxmox prometheus"
