apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: pve-exporter
  namespace: monitoring
spec:
  interval: 30m
  chart:
    spec:
      chart: prometheus-pve-exporter
      version: "2.1.2"
      sourceRef:
        kind: HelmRepository
        name: christianknell
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    image:
      repository: prompve/prometheus-pve-exporter
      tag: 3.6.0@sha256:640f67b7166e266a6dd017162808b5621ee6da931700d581cf91ad988c2ece5b
    env:
      pveAuthType: password
      pveUser: prometheus@pve
      pveExistingSecretName: pve-exporter
      pveVerifySsl: true
    serviceMonitor:
      enabled: true
      namespace: monitoring
      interval: 30s
      metricRelabelings:
        - sourceLabels: [__address__]
          targetLabel: __param_target
        - sourceLabels: [__param_target]
          targetLabel: instance
        - targetLabel: __address__
          replacement: pve-exporter-prometheus-pve-exporter:80
      pveTargets:
        - "novigrad.${HOMELAB_DOMAIN}."
        - "vengerberg.${HOMELAB_DOMAIN}."
        - "oxenfurt.${HOMELAB_DOMAIN}."
        - "rivia.${HOMELAB_DOMAIN}."
        - "cintra.${HOMELAB_DOMAIN}."
