- name: Install packages
  ansible.builtin.package:
    name:
      - zsh
      - git
    state: present
  become: true

- name: Create ZSH config
  ansible.builtin.copy:
    src: zshrc
    dest: "{{ users_created_user.home }}/.zshrc"
    mode: "0644"
    owner: "{{ users_user_login }}"
    group: "{{ users_user_login }}"
  become: true

- name: Create Powerlevel10k config
  ansible.builtin.copy:
    src: p10k.zsh
    dest: "{{ users_created_user.home }}/.p10k.zsh"
    mode: "0644"
    owner: "{{ users_user_login }}"
    group: "{{ users_user_login }}"
  become: true

- name: Create ZSH plugins list
  ansible.builtin.copy:
    src: zsh_plugins.txt
    dest: "{{ users_created_user.home }}/.zsh_plugins.txt"
    mode: "0644"
    owner: "{{ users_user_login }}"
    group: "{{ users_user_login }}"
  become: true
