apiVersion: batch/v1
kind: CronJob
metadata:
  name: regaris
  namespace: life-automations
spec:
  schedule: "21 12 * * 1-5"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: regaris
              image: ghcr.io/andrzej3393/regaris:master
              imagePullPolicy: Always
              envFrom:
                - secretRef:
                    name: regaris
          imagePullSecrets:
            - name: ghcr-pull
          restartPolicy: OnFailure
          dnsConfig:
            options:
              - name: ndots
                value: "1"
