apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name regaris
  namespace: life-automations
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
  data:
    - secretKey: SAGARIS_USERNAME
      remoteRef:
        key: "regaris"
        property: "username"
    - secretKey: SAGARIS_PASSWORD
      remoteRef:
        key: "regaris"
        property: "password"
    - secretKey: HC_UUID
      remoteRef:
        key: "regaris"
        property: "hc_uuid"
    - secretKey: SENTRY_DSN
      remoteRef:
        key: "regaris"
        property: "sentry_dsn"
