---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: home-assistant
  namespace: home-assistant
spec:
  interval: 30m
  chart:
    spec:
      chart: home-assistant
      version: 0.3.21
      sourceRef:
        kind: HelmRepository
        name: home-assistant
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: ghcr.io/home-assistant/home-assistant
      tag: 2025.9.3@sha256:2da8dea31821db443a69d822bd0c47972572fc8379a920a8fac730d2072c8ed2
    env:
      - name: PYTHONPATH
        value: "/config/deps"
    configuration:
      enabled: true
      forceInit: true
      trusted_proxies:
        - 10.42.0.0/16
      templateConfig: |-
        default_config:
        http:
          use_x_forwarded_for: true
          trusted_proxies:
            {{- range .Values.configuration.trusted_proxies }}
            - {{ . }}
            {{- end }}
        frontend:
          themes: !include_dir_merge_named themes
        automation: !include automations.yaml
        script: !include scripts.yaml
        scene: !include scenes.yaml
    securityContext:
      privileged: true
    serviceMonitor:
      enabled: true
    persistence:
      enabled: true
      accessMode: ReadWriteOnce
      size: 1Gi
      storageClass: nfs-ssd
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "home-assistant.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Home Assistant"
        gethomepage.dev/group: "Automations"
        gethomepage.dev/icon: "home-assistant"
      hosts:
        - host: "home-assistant.${HOMELAB_DOMAIN}"
          paths:
            - path: /
              pathType: Prefix
    additionalVolumes:
      - name: dbus
        hostPath:
          path: "/var/run/dbus"
    additionalMounts:
      - mountPath: "/var/run/dbus"
        name: dbus
        readOnly: true
