apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name karakeep
  namespace: karakeep
spec:
  secretStoreRef:
    name: op-connect
    kind: ClusterSecretStore
  target:
    name: *name
  data:
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: "Karakeep"
        property: "nextauth_secret"
    - secretKey: MEILI_MASTER_KEY
      remoteRef:
        key: "Karakeep"
        property: "meili_master_key"
