apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: karakeep
  namespace: karakeep
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    controllers:
      web:
        containers:
          web:
            image:
              repository: ghcr.io/karakeep-app/karakeep
              tag: 0.27.1@sha256:abd7d6b11b1b8fa3593d1971f886a74850ba8d6a99291218b150207d5a60378e
            env:
              MEILI_ADDR: "http://karakeep-meilisearch:7700"
              BROWSER_WEB_URL: "http://karakeep-chrome:9222"
              DATA_DIR: "/data"
              NEXTAUTH_URL: "https://karakeep.${HOMELAB_DOMAIN}"
              DISABLE_SIGNUPS: false
              DISABLE_NEW_RELEASE_CHECK: true
              OLLAMA_BASE_URL: "http://ollama.ai.svc.cluster.local:11434"
              INFERENCE_TEXT_MODEL: "llama3.3"
              INFERENCE_IMAGE_MODEL: "llava"
              INFERENCE_CONTEXT_LENGTH: 12345
              INFERENCE_JOB_TIMEOUT_SEC: 600
              INFERENCE_FETCH_TIMEOUT_SEC: 1200
              CRAWLER_VIDEO_DOWNLOAD: true
              CRAWLER_VIDEO_DOWNLOAD_MAX_SIZE: 2048
              OCR_LANGS: eng,pol,deu
            envFrom:
              - secret: karakeep
      chrome:
        containers:
          chrome:
            image:
              repository: gcr.io/zenika-hub/alpine-chrome
              tag: 124@sha256:1a0046448e0bb6c275c88f86e01faf0de62b02ec8572901256ada0a8c08be23f
            command:
              - chromium-browser
              - --headless
              - --no-sandbox
              - --disable-gpu
              - --disable-dev-shm-usage
              - --remote-debugging-address=0.0.0.0
              - --remote-debugging-port=9222
              - --hide-scrollbars
      meilisearch:
        containers:
          meilisearch:
            image:
              repository: getmeili/meilisearch
              tag: v1.28.2@sha256:71cdfc95cbbe20e99e430f9c955a52f6530833ed25041710fa0b04f8128cfbb3
            command: "/bin/meilisearch"
            args:
              - "--experimental-dumpless-upgrade"
            env:
              MEILI_NO_ANALYTICS: "true"
            envFrom:
              - secret: karakeep
    service:
      web:
        controller: web
        ports:
          http:
            port: 3000
      chrome:
        controller: chrome
        ports:
          http:
            port: 9222
      meilisearch:
        controller: meilisearch
        ports:
          http:
            port: 7700
    ingress:
      main:
        className: nginx
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "karakeep.${HOMELAB_DOMAIN}"
          gethomepage.dev/enabled: "true"
          gethomepage.dev/name: "Karakeep"
          gethomepage.dev/group: "Web"
          gethomepage.dev/icon: "karakeep"
#          gethomepage.dev/widget.type: "karakeep"
#          gethomepage.dev/widget.url: "https://karakeep.${HOMELAB_DOMAIN}"
#          gethomepage.dev/widget.key: "${KARAKEEP_APIKEY}"
        hosts:
          - host: "karakeep.${HOMELAB_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: web
                  port: http
    persistence:
      web:
        existingClaim: karakeep
        advancedMounts:
          web:
            web:
              - path: "/data"
      meilisearch:
        existingClaim: meilisearch
        advancedMounts:
          meilisearch:
            meilisearch:
              - path: "/meili_data"
