apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs-ssd
