---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - home-assistant/kustomization.yaml
  - mosquitto/kustomization.yaml
  - z2m/kustomization.yaml
  - esphome/kustomization.yaml
