apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: nfd
  namespace: hardware
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: "0.17.2"
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    worker:
      config:
        core:
          sources: ["custom", "pci", "usb"]
        sources:
          usb:
            deviceClassWhitelist: ["08"]
            deviceLabelFields: ["class", "vendor", "device"]
