apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nfd
  namespace: hardware
spec:
  interval: 30m
  chart:
    spec:
      chart: node-feature-discovery
      version: "0.19.0"
      sourceRef:
        kind: HelmRepository
        name: nfd
        namespace: flux-system
  maxHistory: 2
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    worker:
      config:
        core:
          featureSources: ["custom", "pci", "usb"]
          labelSources: ["custom", "pci", "usb"]
        sources:
          custom:
            - name: gpu-operator-os-release-labels
              labels:
                feature.node.kubernetes.io/system-os_release.ID: debian
                feature.node.kubernetes.io/system-os_release.VERSION_ID: "12"
              matchFeatures:
                - feature: pci.device
                  matchExpressions:
                    class: { op: InRegexp, value: ["^03"] }
                    vendor: { op: In, value: ["10de"] }
          usb:
            deviceClassWhitelist: ["08"]
            deviceLabelFields: ["class", "vendor", "device"]
