apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: penpot-db
  namespace: penpot
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:15.7
  instances: 1
  storage:
    size: 5Gi
    storageClass: nfs-ssd
