---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homelab-tls
  namespace: ingress-nginx
spec:
  secretName: homelab-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "${HOMELAB_DOMAIN}"
    - "*.${HOMELAB_DOMAIN}"
