apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homepage
  namespace: homepage
spec:
  interval: 30m
  chart:
    spec:
      chart: homepage
      version: 2.0.1
      sourceRef:
        kind: HelmRepository
        name: jameswynn
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    image:
      repository: ghcr.io/gethomepage/homepage
      tag: v1.4.0
    enableRbac: true
    serviceAccount:
      create: true
      name: homepage
    ingress:
      main:
        enabled: true
        annotations:
          external-dns.alpha.kubernetes.io/hostname: "dash.${HOMELAB_DOMAIN}"
        hosts:
          - host: "dash.${HOMELAB_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        ingressClassName: nginx
    env:
      - name: HOMEPAGE_ALLOWED_HOSTS
        value: "dash.${HOMELAB_DOMAIN}"
    config:
      services:
        - Monitoring:
            - Healthchecks.io:
                icon: healthchecks
                href: https://healthchecks.io/
        - Hypervisors:
            - Proxmox:
                icon: proxmox
                href: https://proxmox.${HOMELAB_DOMAIN}:8006/
                ping: https://proxmox.${HOMELAB_DOMAIN}:8006/
                widget:
                  type: proxmox
                  url: https://proxmox.${HOMELAB_DOMAIN}:8006
                  username: "${PROXMOX_HOMEPAGE_API_TOKEN_ID}"
                  password: "${PROXMOX_HOMEPAGE_API_SECRET}"
                  node: proxmox
                  fields: ["resources.cpu", "resources.mem"]
        - IPMI:
            - Supermicro BMC:
                icon: supermicro
                href: https://bmc.${HOMELAB_DOMAIN}/
                ping: https://bmc.${HOMELAB_DOMAIN}/
        - Networking:
            - OPNsense:
                icon: opnsense
                href: https://opnsense.${HOMELAB_DOMAIN}/
                ping: https://opnsense.${HOMELAB_DOMAIN}/
                widget:
                  type: opnsense
                  url: https://opnsense.${HOMELAB_DOMAIN}
                  username: "${OPNSENSE_API_KEY}"
                  password: "${OPNSENSE_API_SECRET}"
            - Switch:
                icon: d-link
                href: http://switch.${HOMELAB_DOMAIN}/
                ping: http://switch.${HOMELAB_DOMAIN}/
            - AP:
                icon: ubiquiti
                href: https://ap.${HOMELAB_DOMAIN}/
                ping: https://ap.${HOMELAB_DOMAIN}/
      widgets:
        - kubernetes:
            cluster:
              show: true
              cpu: true
              memory: true
              showLabel: true
              label: "k3s"
            nodes:
              show: false
        - openmeteo:
            label: Warsaw
            latitude: 52.2297
            longitude: 21.0122
            timezone: Europe/Berlin
            units: metric
            cache: 10
      bookmarks:
      kubernetes:
        mode: default
      settings:
        title: Homelab
        theme: dark
        color: neutral
        useEqualHeights: true
        headerStyle: boxed
        background:
          image: https://wallpapers.com/images/featured-full/berlin-uju0wyyf23ct9bu5.jpg
          #          image: https://r4.wallpaperflare.com/wallpaper/382/840/29/city-poland-night-lights-wallpaper-7132f93582c8bf85addba267d96052b6.jpg
          #          image: https://r0.pxfuel.com/original/132/575/uvuo31uuflnn5ehj5sdtj8etul62cef06372b7e.jpg
          blur: sm
          saturate: 50
          brightness: 50
          opacity: 50
        layout:
          # Services
          - AI:
              tab: Services
              style: row
              columns: 2
          - Automations:
              tab: Services
              style: row
              columns: 2
          - Media:
              tab: Services
              style: row
              columns: 2
          - Web:
              tab: Services
              style: row
              columns: 2
          # Management
          - Monitoring:
              tab: Management
              style: row
              columns: 3
          - Networking:
              tab: Management
              style: row
              columns: 3
          - Hypervisors:
              tab: Management
              style: row
              columns: 1
          - IPMI:
              tab: Management
              style: row
              columns: 1
