apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: penpot
  namespace: penpot
spec:
  interval: 30m
  chart:
    spec:
      chart: penpot
      version: 0.22.0
      sourceRef:
        kind: HelmRepository
        name: penpot
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  uninstall:
    keepHistory: false
  values:
    global:
      redisEnabled: true
    config:
      publicUri: "https://penpot.${HOMELAB_DOMAIN}"
#      flags: "enable-registration enable-login-with-password disable-email-verification enable-smtp"
      telemetryEnabled: false
      postgresql:
        host: "penpot-db-rw"
        port: 5432
        database: "app"
        existingSecret: "penpot-db-app"
        secretKeys:
          usernameKey: "user"
          passwordKey: "password"
      assets:
        storageBackend: "assets-fs"
        filesystem:
          directory: "/opt/data/assets"
    backend:
      image:
        repository: "penpotapp/backend"
        tag: "2.7.2"
    frontend:
      image:
        repository: "penpotapp/frontend"
        tag: "2.7.2"
    exporter:
      image:
        repository: "penpotapp/exporter"
        tag: "2.7.2"
    persistence:
      assets:
        enabled: true
        existingClaim: "penpot-assets"
      exporter:
        enabled: true
        existingClaim: "penpot-exporter"
    ingress:
      enabled: true
      className: nginx
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "penpot.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Penpot"
        gethomepage.dev/group: "Web"
        gethomepage.dev/icon: "penpot"
      path: "/"
      hosts:
        - "penpot.${HOMELAB_DOMAIN}"
