apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: penpot-assets
  namespace: penpot
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs-ssd
  resources:
    requests:
      storage: 20Gi
