apiVersion: external-secrets.io/v1beta1
kind: PushSecret
metadata:
  name: grafana
spec:
  deletionPolicy: "Delete"
  refreshInterval: "10m"
  secretStoreRefs:
    - name: github-andrzej3339-homelab-v2
      kind: SecretStore
  selector:
    secret:
      name: grafana
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: GRAFANA_PASSWORD
