---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-services
  namespace: flux-system
spec:
  path: ./k3s-stable/core/ingress-nginx/external-services/manifests
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: core-substitutions
      - kind: Secret
        name: homepage-substitutions
  dependsOn:
    - name: ingress-nginx
    - name: cluster-config
