---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: z2m
  namespace: home-assistant
spec:
  interval: 30m
  driftDetection:
    mode: enabled
  chart:
    spec:
      chart: zigbee2mqtt
      version: 1.41.0
      sourceRef:
        kind: HelmRepository
        name: z2m
        namespace: flux-system
  install:
    remediation:
      retries: 5
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    image:
      repository: koenkk/zigbee2mqtt
      tag: 1.41.0
    ingress:
      enabled: true
      ingressClassName: nginx
      hosts:
        - host: "zigbee2mqtt.${HOMELAB_DOMAIN}"
          paths:
            - path: /
              pathType: ImplementationSpecific
            - path: /api
              pathType: ImplementationSpecific
      annotations:
        external-dns.alpha.kubernetes.io/hostname: "zigbee2mqtt.${HOMELAB_DOMAIN}"
        gethomepage.dev/enabled: "true"
        gethomepage.dev/name: "Zigbee2MQTT"
        gethomepage.dev/group: "Automations"
        gethomepage.dev/icon: "zigbee2mqtt"
    statefulset:
      storage:
        enabled: true
        storageClassName: nfs-ssd
    zigbee2mqtt:
      mqtt:
        server: "mqtt://mosquitto.home-assistant.svc.cluster.local:8883"
        serial:
          port: "/dev/ttyUSB0"
