---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: healthchecks-io
  namespace: flux-system
spec:
  path: ./flux/apps/monitoring/healthchecks_io/cronjobs
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
  postBuild:
    substituteFrom:
      - kind: Secret
        name: healthchecks-substitutions
  dependsOn:
    - name: cluster-config
