---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  path: ./flux/apps/kyverno/kyverno/app
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  prune: true
  interval: 30m
  retryInterval: 1m
  timeout: 15m
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1
#kind: Kustomization
#metadata:
#  name: kyverno-policies
#  namespace: flux-system
#spec:
#  path: ./flux/apps/kyverno/kyverno/policies
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  wait: true
#  prune: true
#  interval: 10m
#  retryInterval: 1m
#  timeout: 5m
#  dependsOn:
#    - name: kyverno
